---
# roles/jenkins_pxe_job/defaults/main.yml

termux_home: /data/data/com.termux/files/home
jenkins_port: 8080
jenkins_user: admin
# jenkins_password — з vault
# grub-password

jenkins_url: "http://localhost:{{ jenkins_port }}"

job_name: "basic_setup"
