# init/playbooks/roles/jenkins/defaults/main.yaml
termux_prefix: /data/data/com.termux/files
termux_home: "{{ termux_prefix }}/home"
termux_usr: "{{ termux_prefix }}/usr"
termux_bin: "{{ termux_usr }}/bin"

setup_storage: true
update_packages: true
upgrade_packages: true

ssh_port: 8022
enable_sshd: true
start_sshd: true

ssh_permit_root_login: "no"
ssh_password_authentication: "yes"
ssh_pubkey_authentication: "yes"
ssh_allow_users: ""

setup_ssh_keys: true
ssh_key_type: ed25519
ssh_key_comment: "ansible-managed-{{ ansible_hostname }}"

ssh_directory_mode: "0700"
ssh_key_mode: "0600"
ssh_authorized_keys_mode: "0600"

java_home: "{{ termux_usr }}"
openjdk_package_name: "openjdk-21"
jdk_tool_name: "OpenJDK-21"
