---
# roles/jenkins_pxe_job/defaults/main.yml

termux_home: /data/data/com.termux/files/home
jenkins_port: 8080
jenkins_user: admin
# jenkins_password — з vault

jenkins_url: "http://localhost:{{ jenkins_port }}"

job_setup_routeros_name: "routeros-setup"
job_pxe_deploy_name: "pxe-deploy"

# Generic Webhook Trigger токени
gwt_token_routeros: "routeros-setup-token"
gwt_token_pxe: "pxe-deploy-token"