# init/playbooks/roles/termux-base/tasks/copy.yml
- name: Ensure ansible group_vars directory exists
  ansible.builtin.file:
    path: "{{ termux_home }}/ansible/group_vars/all"
    state: directory
    mode: '0755'

- name: Copy ansible vault file
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/ansible/group_vars/all/vault.yaml"
    dest: "{{ termux_home }}/ansible/group_vars/all/vault.yaml"

- name: Copy ansible vault_pass file
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/ansible/.vault_pass"
    dest: "{{ termux_home }}/ansible/.vault_pass"